export enum TableActionType {
  EDIT,
  VIEW,
  DELETE,
  ADD,
  DOWNLOAD,
  DOWNLOADRUECKENNUMMER,
  MAP,
  DOWNLOADLIZENZEN,
  DOWMLOADSCHUSZETTELTAG1,
  DOWMLOADSCHUSZETTELTAG2,
  DOWMLOADSCHUSZETTELTAG3,
  DOWMLOADSCHUSZETTELTAG4,
  COPY
}
