export enum UserRoleEnum {
  ADMIN_ROLE_ID = 1,
  MODERATOR_ROLE_ID,
  USER_ROLE_ID,
  TESTBENUTZER_ROLE_ID,
  TESTMODERATOR_ROLE_ID,
  TEMP_ROLE_ID_SIX,
  LIGALEITER_ROLE_ID,
  SPORTLEITER_ROLE_ID,
  TEAM_MODERATOR_ROLE_ID,
  TEMP_ROLE_ID_TEN,
  AUSRICHTER_ROLE_ID
}


