export enum SchuetzenStatistikType {
  EINZELSTATISTIK = 'EINZELSTATISTIK',
  WETTKAMPFSTATISTIK = 'WETTKAMPFSTATISTIK',
  WETTKAMPFTAGESSTATISTIK = 'WETTKAMPFTAGESSTATISTIK',
  SAISONSTATISTIK = 'SAISONSTATISTIK',
}
