name: Cypress Test
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Cypresss
        run: npm install cypress --save-dev
      - name: Install dependencies
        run: npm ci
      - name: Run Cypress
        build: npm run build
        start: npm start
      - name: Cypress Pipeline
        uses: cypress-io/github-action@v6
        with:
          config-file: cypress.config.ts