name: Cypress Test
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Cypress
        working-directory: bogenliga
        run: npm install cypress --save-dev
      - name: Install dependencies
        working-directory: bogenliga
        run: npm ci
      - name: Run Cypress
        working-directory: bogenliga
        run: npx cypress open
      #- name: Cypress Pipeline
        #uses: cypress-io/github-action@v6

