name: Cypress Test
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Cypress Pipeline
        uses: cypress-io/github-action@v6
        with:
          project: C:\Users\mki4\swt2-projekt\frontend\bogenliga\cypress